smartGPS/Areas/Administration/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Web.WebPages.OAuth;
using smartGPS.Areas.Administration.Models;
using smartGPS.Business;
using smartGPS.Business.ExternalServices;

namespace smartGPS.Areas.Administration.Controllers
{
    public class SignUpController : Controller
    {
        //
        // GET: /Administration/SignUp/

        public ActionResult Index()
        {
            SignUpModel viewModel = new SignUpModel();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(SignUpModel model)
        {
            if (ModelState.IsValid)
            {
                int result = UserAdministration.signUp(model.username, model.password, model.name, model.surname, false, null, null);
                // model is valid, try to sign up user
                if (result == (int)ErrorHandler.SignUpErrors.Success)
                {
                    return RedirectToAction("Index", "SignIn");
                }
                else
                {
                    if (result == (int)ErrorHandler.SignUpErrors.UsernameAlreadyTaken)
                    {
                        ModelState.AddModelError(string.Empty, "Username is already taken!");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "An error has occured while saving to database");
                    }
                    return View(model);
                }
            }
            else
            {
                // model is not valid, return view
                return View(model);
            }
        }
    }
}

smartGPS/Areas/Administration/Views/SignUp/Index.cshtml
@model smartGPS.Areas.Administration.Models.SignUpModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<legend>Sign up to smartGPS</legend>

<div class="tab-content">
    <div class="tab-pane active" id="internal-login">
        @using (Html.BeginForm("Index", "SignUp", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.ValidationSummary(true)
            <div class="control-group">
                @Html.LabelFor(m => m.username, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(m => m.username, new { placeholder = "Username" })
                    @Html.ValidationMessageFor(m => m.username)
                </div>
            </div>
    
            <div class="control-group">
                @Html.LabelFor(m => m.password, new { @class = "control-label" })
                <div class="controls">
                    @Html.PasswordFor(m => m.password, new { placeholder = "Password" })
                    @Html.ValidationMessageFor(m => m.password)
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(m => m.confirmPassword, new { @class = "control-label" })
                <div class="controls">
                    @Html.PasswordFor(m => m.confirmPassword, new { placeholder = "Confirm password" })
                    @Html.ValidationMessageFor(m => m.confirmPassword)
                </div>
            </div>
    
            <div class="control-group">
                @Html.LabelFor(m => m.name, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(m => m.name, new { placeholder = "Name" })
                    @Html.ValidationMessageFor(m => m.name)
                </div>
            </div>
    
            <div class="control-group">
                @Html.LabelFor(m => m.surname, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(m => m.surname, new { placeholder = "Surname" })
                    @Html.ValidationMessageFor(m => m.surname)
                </div>
            </div>
    
            <div class="control-group">
                <div class="controls">
                    <button class="btn btn-large btn-primary" type="submit">Sign up</button>
                </div>
            </div>
        }
    </div>
  
</div>