smartGPS/Areas/Dashboard/Controllers/ExternalServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using smartGPS.Areas.Administration.Models;
using smartGPS.Areas.Dashboard.Models;
using smartGPS.Business;
using smartGPS.Business.ExternalServices;
using smartGPS.Business.Models;
using smartGPS.Business.Models.Facebook;

namespace smartGPS.Areas.Dashboard.Controllers
{
    public class ExternalServicesController : BaseDashboardController
    {

        #region Imported data

        [AllowAnonymous]
        public ActionResult ExternalLoginsList(String provider)
        {
            ViewBag.Provider = provider;
            return PartialView("_ExternalLoginsListPartial", OAuthWebSecurity.RegisteredClientData);
        }

        [AllowAnonymous]
        public ActionResult FacebookLogin()
        {
            return PartialView("_FacebookLogin");
        }

        public ActionResult FoursquareLogin()
        {
            smartGPS.Persistance.FoursquareProfile profile = FourqsquareManagement.getFoursquareProfileData(User.Identity.Name);
            if (profile == null)
            {
                TempData["profile"] = profile;
                return RedirectToAction("ShowFoursquareStatistics", "Profile", new { area = "Dashboard" });
            }
            else
            {
                return PartialView("_FoursquareLogin");
            }
        }


        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult ExternalLogin(string provider, string returnUrl)
        {
            return new ExternalLoginResult(provider, Url.Action("ExternalLoginCallback", new { ReturnUrl = returnUrl }));
        }

           [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult ExternalLoginConfirmation(RegisterExternalLoginModel model, string returnUrl)
        {
            string provider = null;
            string providerUserId = null;
            int result;

            if (User.Identity.IsAuthenticated || !OAuthWebSecurity.TryDeserializeProviderUserId(model.ExternalLoginData, out provider, out providerUserId))
            {
                return RedirectToAction("Manage");
            }


            if (ModelState.IsValid)
            {
              
            }

            ViewBag.ProviderDisplayName = OAuthWebSecurity.GetOAuthClientData(provider).DisplayName;
            return View(model);
        }

        //
        // GET: /Account/ExternalLoginCallback

        [AllowAnonymous]
        public ActionResult ExternalLoginCallback(string returnUrl)
        {

            AuthenticationResult result = OAuthWebSecurity.VerifyAuthentication(Url.Action("ExternalLoginCallback", new { ReturnUrl = returnUrl }));
            if (!result.IsSuccessful)
            {
                return View("ExternalLoginFailure");
            }
            
           
            //if(result.Provider.ToLower().Equals("facebook"))
            //{
            //    Boolean managementResult = FacebookManagement.importFacebookData(result.ProviderUserId, User.Identity.Name);
            //    if(!managementResult)
            //        return View("ExternalLoginFailure");
            //    else
            //        return RedirectToAction("FacebookProfile");
            //}

            return View();
       }

        public ActionResult ExternalLoginFailure()
        {
            return View("ExternalLoginFailure");
        }

        #endregion


        #region Facebook
        [HttpGet]
        public ActionResult FacebookProfile(FacebookStatisticsModel model)
        {
            ViewBag.LoadData = false;
             return View();
        }
        
        [HttpPost]
        public ActionResult FacebookProfile(String dummy)
        {
            ViewBag.LoadData = true;
            return View();
        }

        #endregion


        #region Foursquare
        [HttpGet]
        public ActionResult FoursquareProfile()
        {
            ViewBag.LoadData = false;
            return View();
        }

        [HttpPost]
        public ActionResult FoursquareProfile(String dummy)
        {
            String url = APICalls.getFoursquareAuthTokenUrl();
            return Redirect(url);
        }

        [HttpGet]
        public ActionResult FoursquareResponse(String code)
        {
            Boolean status = FourqsquareManagement.obtainAuthToken(code, User.Identity.Name);
            if (status)
            {
                return RedirectToAction("ShowFoursquareStatistics", "Profile", new { area = "Dashboard" });
            }
            else
            {
                return RedirectToAction("ExternalLoginFailure");
            }
        }

        #endregion


        #region Custom

        internal class ExternalLoginResult : ActionResult
        {
            public ExternalLoginResult(string provider, string returnUrl)
            {
                Provider = provider;
                ReturnUrl = returnUrl;
            }

            public string Provider { get; private set; }
            public string ReturnUrl { get; private set; }

            public override void ExecuteResult(ControllerContext context)
            {
                OAuthWebSecurity.RequestAuthentication(Provider, ReturnUrl);
            }
        }

        #endregion
    }
}

smartGPS/Areas/Dashboard/Views/ExternalServices/ExternalLoginConfirmation.cshtml
@model smartGPS.Areas.Administration.Models.RegisterExternalLoginModel
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<legend>Associate your @ViewBag.ProviderDisplayName account.</legend>

@using (Html.BeginForm("ExternalLoginConfirmation", "SignIn", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

     
    @Html.HiddenFor(m => m.ExternalLoginData)
    <p>
        You've successfully authenticated with <strong>@ViewBag.ProviderDisplayName</strong>.
            Please enter a user name for this site below and click the Confirm button to finish
            logging in.
    </p>
        
    <div class="control-group">
        @Html.LabelFor(m => m.UserName, new { @class = "control-label" })
        <div class="controls">
            @Html.TextBoxFor(m => m.UserName, new { placeholder = "Username" })
            @Html.ValidationMessageFor(m => m.UserName)
        </div>
    </div>
        
    <div class="control-group">
        <div class="controls">
            <button class="btn btn-large btn-primary" type="submit">Register</button>
        </div>
    </div>
}

smartGPS/Areas/Dashboard/Views/ExternalServices/ExternalLoginFailure.cshtml
@{
    ViewBag.Title = "ExternalLoginFailure";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<legend>External login failure</legend>
    <h2>Unsuccessful login with external service.</h2>

smartGPS/Areas/Dashboard/Views/ExternalServices/FacebookProfile.cshtml
@model smartGPS.Areas.Dashboard.Models.FacebookStatisticsModel
@{
    ViewBag.Title = "FacebookProfile";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.LoadData == true)
{
    @Html.Action("FacebookLogin")
}
else
{
    
    <h4>Synchronize your Facebook profile with smartGps</h4><br />
      using (Html.BeginForm("FacebookProfile", "ExternalServices", FormMethod.Post, new { @class = "form-horizontal" }))
      {
           <button class="btn btn-large btn-primary" type="submit">Load data</button>
      }
}
    

smartGPS/Areas/Dashboard/Views/ExternalServices/FoursquareProfile.cshtml
@{
    ViewBag.Title = "FourqsquareProfile";
}

<legend>Foursquare profile</legend>

@if (ViewBag.LoadData == true)
{
    @Html.Action("FoursquareLogin")
}
else
{
      using (Html.BeginForm("FoursquareProfile", "ExternalServices", FormMethod.Post, new { @class = "form-horizontal" }))
      {
           <button class="btn btn-large btn-primary" type="submit">Load data</button>
      }
}

smartGPS/Areas/Dashboard/Views/ExternalServices/_ExternalLoginsListPartial.cshtml
@model ICollection<AuthenticationClientData>

@using (Html.BeginForm("ExternalLogin", "ExternalServices"))
{
    <p>
        Your smartGPS account is not linked with @ViewBag.Provider.
    </p>
    @Html.AntiForgeryToken()
        <p>
            @foreach (AuthenticationClientData p in Model)
            {
                if (p.AuthenticationClient.ProviderName.ToLower().Equals(ViewBag.Provider))
                {
                    <button class="btn btn-large btn-primary" type="submit" name="provider" value="@p.AuthenticationClient.ProviderName" title="Log in using your @p.DisplayName account">Import</button>
                }
            }
        </p>
}

smartGPS/Areas/Dashboard/Views/ExternalServices/_FacebookLogin.cshtml
<div id="fb-root"></div>
<script>
    window.fbAsyncInit = function () {
        FB.init({
            appId: '526242434133615', // App ID
            status: true, // check login status
            cookie: true, // enable cookies to allow the server to access the session
            xfbml: true  // parse XFBML
        });

        // Here we subscribe to the auth.authResponseChange JavaScript event. This event is fired
        // for any authentication related change, such as login, logout or session refresh. This means that
        // whenever someone who was previously logged out tries to log in again, the correct case below 
        // will be handled. 

        var token;

        FB.Event.subscribe('auth.authResponseChange', function (response) {
            // Here we specify what we do with the response anytime this event occurs. 
            if (response.status === 'connected') {
                // The response object is returned with a status field that lets the app know the current
                // login status of the person. In this case, we're handling the situation where they 
                // have logged in to the app.
                token = response.authResponse.accessToken;
                testAPI(token);
            } else if (response.status === 'not_authorized') {
                // In this case, the person is logged into Facebook, but not into the app, so we call
                // FB.login() to prompt them to do so. 
                // In real-life usage, you wouldn't want to immediately prompt someone to login 
                // like this, for two reasons:
                // (1) JavaScript created popup windows are blocked by most browsers unless they 
                // result from direct interaction from people using the app (such as a mouse click)
                // (2) it is a bad experience to be continually prompted to login upon page load.
                FB.login(function (response) {
                    if (response.authResponse) {
                        console.log('Welcome!  Fetching your information.... ');
                        FB.api('/me', function (response) {
                            console.log('Good to see you, ' + response.name + '.');
                        });
                    } else {
                        console.log('User cancelled login or did not fully authorize.');
                    }
                }, { scope: 'email,user_likes' });
            } else {
                // In this case, the person is not logged into Facebook, so we call the login() 
                // function to prompt them to do so. Note that at this stage there is no indication
                // of whether they are logged into the app. If they aren't then they'll see the Login
                // dialog right after they log in to Facebook. 
                // The same caveats as above apply to the FB.login() call here.
                FB.login(function (response) {
                    if (response.authResponse) {
                        console.log('Welcome!  Fetching your information.... ');
                        FB.api('/me', function (response) {
                            console.log('Good to see you, ' + response.name + '.');
                        });
                    } else {
                        console.log('User cancelled login or did not fully authorize.');
                    }
                }, { scope: 'email,user_likes' });
            }
        });
    };

    // Load the SDK asynchronously
    (function (d) {
        var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
        if (d.getElementById(id)) { return; }
        js = d.createElement('script'); js.id = id; js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        ref.parentNode.insertBefore(js, ref);
    }(document));

    // Here we run a very simple test of the Graph API after login is successful. 
    // This testAPI() function is only called in those cases. 
    function testAPI(token) {

        var data = new Object();
        data.token = token;
        var url;
        if (window.location.port == null)
            url = window.location.hostname + "/Dashboard/Profile/FacebookStatistics";
        else
            url = window.location.hostname + ":" + window.location.port + "/Dashboard/Profile/FacebookStatistics";
        url = "http://" + url;

        window.location.href = url + "?token=" + token;

        //$.ajax({
        //    url: (url),
        //    type: ("GET"),
        //    data: { token : token },
        //    success: console.log('success'),
        //    error: console.log('error')
        //});


        //console.log('Welcome!  Fetching your information.... ');
        //FB.api('/me', function (response) {
        //    console.log('Good to see you, ' + response.name + '.');
        //});
    }
</script>

<!--
  Below we include the Login Button social plugin. This button uses the JavaScript SDK to
  present a graphical Login button that triggers the FB.login() function when clicked.

  Learn more about options for the login button plugin:
  /docs/reference/plugins/login/ -->

<div class="fb-login-button" data-show-faces="true" data-width="400" data-max-rows="1" data-scope="user_likes, user_actions.books, user_actions.video, user_checkins, user_friends, user_status, user_actions.music, friends_checkins, friends_interests, friends_likes"></div>

smartGPS/Areas/Dashboard/Views/ExternalServices/_FoursquareLogin.cshtml
<script>
    
    $(document).ready(function () {

        var clientId = "V22JFGZJFGU0N1EI2XPLWTCZMOMY5KPCMFZ0DUK05JPI0EVS";
        var redirect_url = "http://localhost:5188/Dashboard/ExternalServices/FoursquareResponse";
        var url = "https://foursquare.com/oauth2/authenticate?client_id=" + clientId+"&response_type=code&redirect_uri=" + redirect_url;

        $.ajax({
            url: ("Travel/GetAddressByGPSCoordinates"),
            type: ("GET"),
             success: function (data) {
                 refresh();
            }
        });

    });

    function refresh(data) {
    }
        
</script>