smartGPS/Areas/Administration/Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using smartGPS.Areas.Administration.Models;
using smartGPS.Business;

namespace smartGPS.Areas.Administration.Controllers
{
    public class SignInController : Controller
    {
        //
        // GET: /Administration/Home/

        public ActionResult Index()
        {
            SignInModel model = new SignInModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(SignInModel model)
        {
            if (ModelState.IsValid)
            {
                int result = UserAdministration.signIn(model.username, model.password, model.remeberMe);
                // model is valid, try to sign up user
                if (result == (int)ErrorHandler.SignUpErrors.Success)
                {
                    return RedirectToAction("Index", "Dashboard", new { area = "Dashboard" });
                }
                else
                {
                    if (result == (int)ErrorHandler.SignInErrors.Failed)
                    {
                        ModelState.AddModelError(string.Empty, "Username or password is not correct!");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "An error has occured while saving to database");
                    }
                    return View(model);
                }
            }
            else
            {
                // model is not valid, return view
                return View(model);
            }
        }
    }
}

smartGPS/Areas/Administration/Views/SignIn/Index.cshtml
@model smartGPS.Areas.Administration.Models.SignInModel

@{
    ViewBag.Title = "Sign in";
    Layout = "";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Sign in &middot; smartGPS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles --> 
    <link href="~/Content/themes/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <style type="text/css">
        body
        {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin
        {
            max-width: 300px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
        }

            .form-signin .form-signin-heading,
            .form-signin .checkbox
            {
                margin-bottom: 10px;
            }

            .form-signin input[type="text"],
            .form-signin input[type="password"]
            {
                font-size: 16px;
                height: auto;
                margin-bottom: 15px;
                padding: 7px 9px;
            }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">

        @Html.ValidationSummary(true)
        
        @using (Html.BeginForm("Index", "SignIn", FormMethod.Post, new { @class = "form-signin"}))
        {
            <h2 class="form-signin-heading">smartGPS Sign in</h2>
             @Html.TextBoxFor(m => m.username, new { @class = "input-block-level", placeholder = "Username" })
             @Html.PasswordFor(m => m.password, new { @class = "input-block-level", placeholder = "Password" })
          
             <label class="checkbox">
                @Html.CheckBoxFor(m => m.remeberMe)
                @Html.LabelFor(m => m.remeberMe)
            </label>
             <button class="btn btn-large btn-primary" type="submit">Sign in</button>
        }
        
    </div>
    <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>